from PyQt6.QtGui import QFont

font2 = QFont()
font2.setFamily(u"Segoe UI")
font2.setPointSize(8)
font2.setBold(False)
font2.setItalic(False)
font1 = QFont()
font1.setFamily(u"Segoe UI Semibold")
font1.setPointSize(12)
font1.setBold(False)
font1.setItalic(False)
font = QFont()
font.setFamily(u"Segoe UI")
font.setPointSize(10)
font.setBold(False)
font.setItalic(False)
font3 = QFont()
font3.setFamily(u"Segoe UI")
font3.setPointSize(10)
font3.setBold(False)
font3.setItalic(False)
font3.setStyleStrategy(QFont.StyleStrategy.PreferDefault)
font5 = QFont()
font5.setFamily(u"Segoe UI")
font5.setBold(False)
font5.setItalic(False)